[package]
name = "x509-parser"
version = "0.1.0"
description = "Parser for BER/DER encoding data"
license = "MIT/Apache-2.0"
keywords = ["X.509","Certificate","parser","nom"]
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
homepage = "https://github.com/rusticata/x509-parser"
repository = "https://github.com/rusticata/x509-parser.git"
categories = ["parsing"]

[lib]
name = "x509_parser"

[dependencies]
nom = {version = "^3.1", features=["verbose-errors"] }
rusticata-macros = "^0.4"
num = "0.1"
time = "0.1"
der-parser = { version = "^0.5.0", features=["bigint"] }

# [dependencies.der-parser]
# path = "../der-parser"
# features = ["bigint"]
