[package]
name = "x509-parser"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[lib]
name = "x509_parser"

[dependencies]
nom = {version = "^2.0", features=["verbose-errors"] }
rusticata-macros = "^0"
der-parser = "^0"

# [dependencies.der-parser]
# path = "../der-parser"
