[package]
name = "x509-parser"
version = "0.2.0"
description = "Parser for the X.509 v3 format (RFC 5280 certificates)"
license = "MIT/Apache-2.0"
keywords = ["X509","Certificate","parser","nom"]
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
homepage = "https://github.com/rusticata/x509-parser"
repository = "https://github.com/rusticata/x509-parser.git"
categories = ["parsing"]

include = [
  "LICENSE-*",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "src/*.rs",
  "tests/*.rs",
  "assets/*.der"
]

[dependencies]
base64 = "0.9.0"
nom = {version = "4.0", features=["verbose-errors"] }
rusticata-macros = "1.0"
num = "0.1"
time = "0.1"
der-parser = {version="0.6.0", git='https://github.com/rusticata/der-parser.git', branch='nom4', features=["bigint"] }

[badges]
travis-ci = { repository = "rusticata/x509-parser" }
