[package]
name = "x509-parser"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[lib]
name = "x509_parser"

[dependencies]
nom = {version = "^3.1", features=["verbose-errors"] }
rusticata-macros = "^0"
num = "0.1"
time = "0.1"
der-parser = { version = "^0.4.2", features=["bigint"] }

# [dependencies.der-parser]
# path = "../der-parser"
# features = ["bigint"]
